Upgrade maven version to 3.9.9 on Dockerfile
quarkus-qe/quarkus-openshift-interop pull request #17
Opened 2024-12-17 09:22 UTC by jcarranzan

As part of the task to upgrade maven to 3.9.9, most of our repositories where Maven have been already updated to 3.9.9.
Here has been modified the `MAVEN_VERSION` to 3.9.9 and the links related to the Dockerfile.

2024-12-17 10:29 UTC, fedinskiy requested changes

2024-12-17 10:29 UTC, fedinskiy commented on openshift-ci/Dockerfile
> +RUN curl https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz.sha512 > maven.sha512 && printf "\tmaven.tar.gz" >> maven.sha512 && sha512sum -c maven.sha512
Could you reuse MAVEN_VERSION here?

2024-12-17 10:29 UTC, fedinskiy commented
/test all

2024-12-17 10:42 UTC, jcarranzan commented
/test all

2024-12-17 11:27 UTC, fedinskiy approved these changes
But let's wait for green CI

2024-12-17 12:42 UTC, jcarranzan commented
@fedinskiy, do you have any idea why these kinds of timeout failures occur?

2024-12-17 13:07 UTC, fedinskiy commented
@jcarranzan it looks like there are too many jobs active right now

2024-12-17 14:38 UTC, jcarranzan commented
/test all

2024-12-18 07:26 UTC, jcarranzan commented
/retest

2024-12-18 13:25 UTC, merged